### ISSUE TITLE
Error while creating csv files through: dataset.create_single_domain_filelist

### ISSUE THREAD

**Issue by gunshi** [leehomyc/Img2Img-Translation-Networks#2]
Hey, facing the following error when trying to generate csv files:

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tushar/codes/gunsshi/Img2Img-Translation-Networks/dataset/create_single_domain_filelist.py", line 9, in <module>
    @click.command()
AttributeError: 'module' object has no attribute 'command'

The error may be related to the ambiguous naming of the module click clashing with the library import, but not sure.

**Comment by gunshi** [comment]
Upgrading/Reinstalling fixes issue, thanks.
